version: '3'

services:
  db:
    image: postgres:10.5-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
  app:
    image: 'ifrn/suap-sso:1.0'
    build:
      context: ../dockers/suapsso
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    env_file:
      - .env
    volumes:
      - '../apps:/apps'
    depends_on:
      - db
